// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

/**
 * @title LastWishVault
 * @dev A decentralized digital legacy vault contract.
 * Implements owner heartbeats, a safety veto grace period, and whitelisted recipient retrieval.
 */
contract LastWishVault {
    
    enum Status { ACTIVE, PENDING_UNLOCK, UNLOCKED }

    struct Vault {
        address owner;
        address recipient;
        uint256 inactivityPeriod; // In seconds
        uint256 gracePeriod;      // In seconds (Veto grace window)
        uint256 lastHeartbeat;    // Block timestamp of last heartbeat/check-in
        string share1;            // The encrypted/locked Shamir key share
        string ipfsHash;          // The IPFS Content Identifier (CID) of the encrypted payload
        Status status;            // Current cached status (evaluated dynamically on read)
    }

    // Mapping of Vault ID (bytes32 hash) to Vault details
    mapping(bytes32 => Vault) private vaults;

    // Events
    event VaultCreated(bytes32 indexed vaultId, address indexed owner, address indexed recipient, uint256 inactivityPeriod, uint256 gracePeriod);
    event HeartbeatUpdated(bytes32 indexed vaultId, uint256 timestamp);
    event VetoExecuted(bytes32 indexed vaultId, uint256 timestamp);
    event ShareClaimed(bytes32 indexed vaultId, address indexed recipient);

    // Modifiers
    modifier onlyVaultOwner(bytes32 vaultId) {
        require(vaults[vaultId].owner == msg.sender, "LastWishVault: Only the vault owner can perform this action.");
        _;
    }

    modifier onlyVaultRecipient(bytes32 vaultId) {
        require(vaults[vaultId].recipient == msg.sender, "LastWishVault: Only the designated recipient can perform this action.");
        _;
    }

    modifier vaultExists(bytes32 vaultId) {
        require(vaults[vaultId].owner != address(0), "LastWishVault: Vault does not exist.");
        _;
    }

    /**
     * @notice Deploys a new legacy vault on-chain.
     * @param vaultId Unique identifier generated by the client (hash of name/details).
     * @param recipient Address of the designated beneficiary.
     * @param inactivityPeriod Duration in seconds of allowed inactivity.
     * @param gracePeriod Duration in seconds of the veto window.
     * @param share1 The locked Shamir key share (Share 1).
     * @param ipfsHash IPFS CID of the encrypted files.
     */
    function createVault(
        bytes32 vaultId,
        address recipient,
        uint256 inactivityPeriod,
        uint256 gracePeriod,
        string calldata share1,
        string calldata ipfsHash
    ) external {
        require(vaults[vaultId].owner == address(0), "LastWishVault: Vault ID already exists.");
        require(recipient != address(0), "LastWishVault: Recipient address cannot be the zero address.");
        require(inactivityPeriod > 0, "LastWishVault: Inactivity period must be greater than zero.");
        
        vaults[vaultId] = Vault({
            owner: msg.sender,
            recipient: recipient,
            inactivityPeriod: inactivityPeriod,
            gracePeriod: gracePeriod,
            lastHeartbeat: block.timestamp,
            share1: share1,
            ipfsHash: ipfsHash,
            status: Status.ACTIVE
        });

        emit VaultCreated(vaultId, msg.sender, recipient, inactivityPeriod, gracePeriod);
    }

    /**
     * @notice Resets the inactivity timer. Can be called regularly to prove owner is active.
     */
    function heartbeat(bytes32 vaultId) external onlyVaultOwner(vaultId) vaultExists(vaultId) {
        vaults[vaultId].lastHeartbeat = block.timestamp;
        
        emit HeartbeatUpdated(vaultId, block.timestamp);
    }

    /**
     * @notice Explicit veto command to halt a pending release and reset the timer.
     */
    function veto(bytes32 vaultId) external onlyVaultOwner(vaultId) vaultExists(vaultId) {
        // Reset timer
        vaults[vaultId].lastHeartbeat = block.timestamp;
        
        emit VetoExecuted(vaultId, block.timestamp);
    }

    /**
     * @notice Dynamically calculates the current vault status using lazy evaluation.
     */
    function getVaultStatus(bytes32 vaultId) public view vaultExists(vaultId) returns (Status) {
        Vault memory vault = vaults[vaultId];
        uint256 elapsed = block.timestamp - vault.lastHeartbeat;

        if (elapsed >= vault.inactivityPeriod + vault.gracePeriod) {
            return Status.UNLOCKED;
        } else if (elapsed >= vault.inactivityPeriod) {
            return Status.PENDING_UNLOCK;
        } else {
            return Status.ACTIVE;
        }
    }

    /**
     * @notice Exposes public read metadata of a vault (excluding the private key share).
     */
    function getVaultDetails(bytes32 vaultId) external view vaultExists(vaultId) returns (
        address owner,
        address recipient,
        uint256 inactivityPeriod,
        uint256 gracePeriod,
        uint256 lastHeartbeat,
        string memory ipfsHash,
        Status status
    ) {
        Vault memory vault = vaults[vaultId];
        Status currentStatus = getVaultStatus(vaultId);
        return (
            vault.owner,
            vault.recipient,
            vault.inactivityPeriod,
            vault.gracePeriod,
            vault.lastHeartbeat,
            vault.ipfsHash,
            currentStatus
        );
    }

    /**
     * @notice Retrives locked Share 1 for the recipient. Only succeeds if inactivity & grace periods have expired.
     */
    function claimVaultShare(bytes32 vaultId) external view onlyVaultRecipient(vaultId) vaultExists(vaultId) returns (string memory) {
        Vault memory vault = vaults[vaultId];
        uint256 elapsed = block.timestamp - vault.lastHeartbeat;
        
        // Ensure both the inactivity trigger AND the veto grace window have fully elapsed on-chain
        require(
            elapsed >= vault.inactivityPeriod + vault.gracePeriod,
            "LastWishVault: Vault is locked. Inactivity period and grace window must expire before retrieval."
        );

        return vault.share1;
    }
}
