// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

/**
 * @title LastWishVault
 * @dev A decentralized digital legacy vault contract supporting multiple recipients,
 * categorized payloads, owner heartbeats, and dynamic unlock statuses per recipient.
 */
contract LastWishVault {
    
    enum Status { ACTIVE, PENDING_UNLOCK, UNLOCKED }

    struct RecipientConfig {
        address recipient;
        string category;          // e.g. "Finances", "Memories", "Medical"
        uint256 inactivityPeriod; // In seconds (for demo)
        uint256 gracePeriod;      // In seconds (veto grace window)
        string share1;            // Locked Shamir key share
        string ipfsHash;          // IPFS CID containing ciphertext for this category
    }

    struct Vault {
        address owner;
        uint256 lastHeartbeat;    // Block timestamp of last heartbeat/check-in
        bool exists;
    }

    // Mapping of Vault ID (bytes32 hash) to Vault basic details
    mapping(bytes32 => Vault) private vaults;

    // Mapping of Vault ID to list of recipient configurations
    mapping(bytes32 => RecipientConfig[]) private vaultRecipients;

    // Events
    event VaultCreated(bytes32 indexed vaultId, address indexed owner, uint256 recipientCount);
    event HeartbeatUpdated(bytes32 indexed vaultId, uint256 timestamp);
    event VetoExecuted(bytes32 indexed vaultId, uint256 timestamp);
    event ShareClaimed(bytes32 indexed vaultId, address indexed recipient, string category);

    // Modifiers
    modifier onlyVaultOwner(bytes32 vaultId) {
        require(vaults[vaultId].owner == msg.sender, "LastWishVault: Only the vault owner can perform this action.");
        _;
    }

    modifier vaultExists(bytes32 vaultId) {
        require(vaults[vaultId].exists, "LastWishVault: Vault does not exist.");
        _;
    }

    /**
     * @notice Deploys a new legacy vault on-chain with multiple recipient configurations.
     * @param vaultId Unique identifier generated by the client.
     * @param configs Array of recipient configurations.
     */
    function createVault(
        bytes32 vaultId,
        RecipientConfig[] calldata configs
    ) external {
        require(!vaults[vaultId].exists, "LastWishVault: Vault ID already exists.");
        require(configs.length > 0, "LastWishVault: Must configure at least one recipient.");

        vaults[vaultId] = Vault({
            owner: msg.sender,
            lastHeartbeat: block.timestamp,
            exists: true
        });

        for (uint256 i = 0; i < configs.length; i++) {
            require(configs[i].recipient != address(0), "LastWishVault: Recipient address cannot be the zero address.");
            require(configs[i].inactivityPeriod > 0, "LastWishVault: Inactivity period must be greater than zero.");
            vaultRecipients[vaultId].push(configs[i]);
        }

        emit VaultCreated(vaultId, msg.sender, configs.length);
    }

    /**
     * @notice Resets the inactivity timer. Can be called regularly to prove owner is active.
     */
    function heartbeat(bytes32 vaultId) external onlyVaultOwner(vaultId) vaultExists(vaultId) {
        vaults[vaultId].lastHeartbeat = block.timestamp;
        emit HeartbeatUpdated(vaultId, block.timestamp);
    }

    /**
     * @notice Explicit veto command to halt a pending release and reset the timer.
     */
    function veto(bytes32 vaultId) external onlyVaultOwner(vaultId) vaultExists(vaultId) {
        vaults[vaultId].lastHeartbeat = block.timestamp;
        emit VetoExecuted(vaultId, block.timestamp);
    }

    /**
     * @notice Exposes public read metadata of a vault.
     */
    function getVaultDetails(bytes32 vaultId) external view vaultExists(vaultId) returns (
        address owner,
        uint256 lastHeartbeat,
        uint256 recipientCount
    ) {
        Vault memory vault = vaults[vaultId];
        return (
            vault.owner,
            vault.lastHeartbeat,
            vaultRecipients[vaultId].length
        );
    }

    /**
     * @notice Exposes public list of all recipient configurations under this vault.
     */
    function getVaultRecipients(bytes32 vaultId) external view vaultExists(vaultId) returns (RecipientConfig[] memory) {
        return vaultRecipients[vaultId];
    }

    /**
     * @notice Dynamically calculates the current status of a specific configuration.
     */
    function getRecipientStatus(bytes32 vaultId, address recipient, string calldata category) public view vaultExists(vaultId) returns (Status) {
        Vault memory vault = vaults[vaultId];
        uint256 elapsed = block.timestamp - vault.lastHeartbeat;

        uint256 length = vaultRecipients[vaultId].length;
        for (uint256 i = 0; i < length; i++) {
            RecipientConfig memory config = vaultRecipients[vaultId][i];
            if (config.recipient == recipient && keccak256(bytes(config.category)) == keccak256(bytes(category))) {
                if (elapsed >= config.inactivityPeriod + config.gracePeriod) {
                    return Status.UNLOCKED;
                } else if (elapsed >= config.inactivityPeriod) {
                    return Status.PENDING_UNLOCK;
                } else {
                    return Status.ACTIVE;
                }
            }
        }
        revert("LastWishVault: Configuration not found.");
    }

    /**
     * @notice Retrieves locked Share 1 for the calling recipient/category. Only succeeds if inactivity & grace periods have expired.
     */
    function claimVaultShare(bytes32 vaultId, string calldata category) external view vaultExists(vaultId) returns (string memory) {
        Vault memory vault = vaults[vaultId];
        uint256 elapsed = block.timestamp - vault.lastHeartbeat;
        
        uint256 length = vaultRecipients[vaultId].length;
        for (uint256 i = 0; i < length; i++) {
            RecipientConfig memory config = vaultRecipients[vaultId][i];
            if (config.recipient == msg.sender && keccak256(bytes(config.category)) == keccak256(bytes(category))) {
                // Ensure both the inactivity trigger AND the veto grace window have fully elapsed on-chain
                require(
                    elapsed >= config.inactivityPeriod + config.gracePeriod,
                    "LastWishVault: Vault is locked. Inactivity period and grace window must expire before retrieval."
                );
                return config.share1;
            }
        }
        
        revert("LastWishVault: Caller is not a recipient for this category, or vault is locked.");
    }
}
